### ISSUE TITLE
Translations editions for Polish WS-gram pilot 2

### ISSUE THREAD

**Issue by gkrajewski** [gkrajewski/CDI-online#304]
- [x] W instrukcji do części leksykalnej fragment o komentarzach jest nieadekwatny do tej aplikacji (nie ma komentarzy dla każdego słowa oddzielnie).
- [x] Potrzebna jest drobna redakcja instrukcji do części leksykalnej
- [x] Uwagi (stan faktyczny) czy komentarze (w przynajmniej jednej instrukcji)

**Comment by karolina-m** [comment]
MK przygotowała tu: https://docs.google.com/document/d/1GPia0lnzoA7TqIlRJjPCLh1-oUnrdByzO4bmeLyiMi0/edit?
A tu Issue w którym listujemy co jest jeszcze do poprawki: https://github.com/karolina-m/irmiksiz_gram/issues/14
